// Country data with flags and continents
const countries = [
    { name: "Afghanistan", continent: "Asia", flag: "🇦🇫" },
    { name: "Albania", continent: "Europe", flag: "🇦🇱" },
    { name: "Algeria", continent: "Africa", flag: "🇩🇿" },
    { name: "Andorra", continent: "Europe", flag: "🇦🇩" },
    { name: "Angola", continent: "Africa", flag: "🇦🇴" },
    { name: "Antigua and Barbuda", continent: "North America", flag: "🇦🇬" },
    { name: "Argentina", continent: "South America", flag: "🇦🇷" },
    { name: "Armenia", continent: "Asia", flag: "🇦🇲" },
    { name: "Australia", continent: "Oceania", flag: "🇦🇺" },
    { name: "Austria", continent: "Europe", flag: "🇦🇹" },
    { name: "Azerbaijan", continent: "Asia", flag: "🇦🇿" },
    { name: "Bahamas", continent: "North America", flag: "🇧🇸" },
    { name: "Bahrain", continent: "Asia", flag: "🇧🇭" },
    { name: "Bangladesh", continent: "Asia", flag: "🇧🇩" },
    { name: "Barbados", continent: "North America", flag: "🇧🇧" },
    { name: "Belarus", continent: "Europe", flag: "🇧🇾" },
    { name: "Belgium", continent: "Europe", flag: "🇧🇪" },
    { name: "Belize", continent: "North America", flag: "🇧🇿" },
    { name: "Benin", continent: "Africa", flag: "🇧🇯" },
    { name: "Bhutan", continent: "Asia", flag: "🇧🇹" },
    { name: "Bolivia", continent: "South America", flag: "🇧🇴" },
    { name: "Bosnia and Herzegovina", continent: "Europe", flag: "🇧🇦" },
    { name: "Botswana", continent: "Africa", flag: "🇧🇼" },
    { name: "Brazil", continent: "South America", flag: "🇧🇷" },
    { name: "Brunei", continent: "Asia", flag: "🇧🇳" },
    { name: "Bulgaria", continent: "Europe", flag: "🇧🇬" },
    { name: "Burkina Faso", continent: "Africa", flag: "🇧🇫" },
    { name: "Burundi", continent: "Africa", flag: "🇧🇮" },
    { name: "Cabo Verde", continent: "Africa", flag: "🇨🇻" },
    { name: "Cambodia", continent: "Asia", flag: "🇰🇭" },
    { name: "Cameroon", continent: "Africa", flag: "🇨🇲" },
    { name: "Canada", continent: "North America", flag: "🇨🇦" },
    { name: "Central African Republic", continent: "Africa", flag: "🇨🇫" },
    { name: "Chad", continent: "Africa", flag: "🇹🇩" },
    { name: "Chile", continent: "South America", flag: "🇨🇱" },
    { name: "China", continent: "Asia", flag: "🇨🇳" },
    { name: "Colombia", continent: "South America", flag: "🇨🇴" },
    { name: "Comoros", continent: "Africa", flag: "🇰🇲" },
    { name: "Congo", continent: "Africa", flag: "🇨🇬" },
    { name: "Costa Rica", continent: "North America", flag: "🇨🇷" },
    { name: "Croatia", continent: "Europe", flag: "🇭🇷" },
    { name: "Cuba", continent: "North America", flag: "🇨🇺" },
    { name: "Cyprus", continent: "Europe", flag: "🇨🇾" },
    { name: "Czech Republic", continent: "Europe", flag: "🇨🇿" },
    { name: "Denmark", continent: "Europe", flag: "🇩🇰" },
    { name: "Djibouti", continent: "Africa", flag: "🇩🇯" },
    { name: "Dominica", continent: "North America", flag: "🇩🇲" },
    { name: "Dominican Republic", continent: "North America", flag: "🇩🇴" },
    { name: "Ecuador", continent: "South America", flag: "🇪🇨" },
    { name: "Egypt", continent: "Africa", flag: "🇪🇬" },
    { name: "El Salvador", continent: "North America", flag: "🇸🇻" },
    { name: "Equatorial Guinea", continent: "Africa", flag: "🇬🇶" },
    { name: "Eritrea", continent: "Africa", flag: "🇪🇷" },
    { name: "Estonia", continent: "Europe", flag: "🇪🇪" },
    { name: "Eswatini", continent: "Africa", flag: "🇸🇿" },
    { name: "Ethiopia", continent: "Africa", flag: "🇪🇹" },
    { name: "Fiji", continent: "Oceania", flag: "🇫🇯" },
    { name: "Finland", continent: "Europe", flag: "🇫🇮" },
    { name: "France", continent: "Europe", flag: "🇫🇷" },
    { name: "Gabon", continent: "Africa", flag: "🇬🇦" },
    { name: "Gambia", continent: "Africa", flag: "🇬🇲" },
    { name: "Georgia", continent: "Asia", flag: "🇬🇪" },
    { name: "Germany", continent: "Europe", flag: "🇩🇪" },
    { name: "Ghana", continent: "Africa", flag: "🇬🇭" },
    { name: "Greece", continent: "Europe", flag: "🇬🇷" },
    { name: "Grenada", continent: "North America", flag: "🇬🇩" },
    { name: "Guatemala", continent: "North America", flag: "🇬🇹" },
    { name: "Guinea", continent: "Africa", flag: "🇬🇳" },
    { name: "Guinea-Bissau", continent: "Africa", flag: "🇬🇼" },
    { name: "Guyana", continent: "South America", flag: "🇬🇾" },
    { name: "Haiti", continent: "North America", flag: "🇭🇹" },
    { name: "Honduras", continent: "North America", flag: "🇭🇳" },
    { name: "Hungary", continent: "Europe", flag: "🇭🇺" },
    { name: "Iceland", continent: "Europe", flag: "🇮🇸" },
    { name: "India", continent: "Asia", flag: "🇮🇳" },
    { name: "Indonesia", continent: "Asia", flag: "🇮🇩" },
    { name: "Iran", continent: "Asia", flag: "🇮🇷" },
    { name: "Iraq", continent: "Asia", flag: "🇮🇶" },
    { name: "Ireland", continent: "Europe", flag: "🇮🇪" },
    { name: "Israel", continent: "Asia", flag: "🇮🇱" },
    { name: "Italy", continent: "Europe", flag: "🇮🇹" },
    { name: "Jamaica", continent: "North America", flag: "🇯🇲" },
    { name: "Japan", continent: "Asia", flag: "🇯🇵" },
    { name: "Jordan", continent: "Asia", flag: "🇯🇴" },
    { name: "Kazakhstan", continent: "Asia", flag: "🇰🇿" },
    { name: "Kenya", continent: "Africa", flag: "🇰🇪" },
    { name: "Kiribati", continent: "Oceania", flag: "🇰🇮" },
    { name: "Kuwait", continent: "Asia", flag: "🇰🇼" },
    { name: "Kyrgyzstan", continent: "Asia", flag: "🇰🇬" },
    { name: "Laos", continent: "Asia", flag: "🇱🇦" },
    { name: "Latvia", continent: "Europe", flag: "🇱🇻" },
    { name: "Lebanon", continent: "Asia", flag: "🇱🇧" },
    { name: "Lesotho", continent: "Africa", flag: "🇱🇸" },
    { name: "Liberia", continent: "Africa", flag: "🇱🇷" },
    { name: "Libya", continent: "Africa", flag: "🇱🇾" },
    { name: "Liechtenstein", continent: "Europe", flag: "🇱🇮" },
    { name: "Lithuania", continent: "Europe", flag: "🇱🇹" },
    { name: "Luxembourg", continent: "Europe", flag: "🇱🇺" },
    { name: "Madagascar", continent: "Africa", flag: "🇲🇬" },
    { name: "Malawi", continent: "Africa", flag: "🇲🇼" },
    { name: "Malaysia", continent: "Asia", flag: "🇲🇾" },
    { name: "Maldives", continent: "Asia", flag: "🇲🇻" },
    { name: "Mali", continent: "Africa", flag: "🇲🇱" },
    { name: "Malta", continent: "Europe", flag: "🇲🇹" },
    { name: "Marshall Islands", continent: "Oceania", flag: "🇲🇭" },
    { name: "Mauritania", continent: "Africa", flag: "🇲🇷" },
    { name: "Mauritius", continent: "Africa", flag: "🇲🇺" },
    { name: "Mexico", continent: "North America", flag: "🇲🇽" },
    { name: "Micronesia", continent: "Oceania", flag: "🇫🇲" },
    { name: "Moldova", continent: "Europe", flag: "🇲🇩" },
    { name: "Monaco", continent: "Europe", flag: "🇲🇨" },
    { name: "Mongolia", continent: "Asia", flag: "🇲🇳" },
    { name: "Montenegro", continent: "Europe", flag: "🇲🇪" },
    { name: "Morocco", continent: "Africa", flag: "🇲🇦" },
    { name: "Mozambique", continent: "Africa", flag: "🇲🇿" },
    { name: "Myanmar", continent: "Asia", flag: "🇲🇲" },
    { name: "Namibia", continent: "Africa", flag: "🇳🇦" },
    { name: "Nauru", continent: "Oceania", flag: "🇳🇷" },
    { name: "Nepal", continent: "Asia", flag: "🇳🇵" },
    { name: "Netherlands", continent: "Europe", flag: "🇳🇱" },
    { name: "New Zealand", continent: "Oceania", flag: "🇳🇿" },
    { name: "Nicaragua", continent: "North America", flag: "🇳🇮" },
    { name: "Niger", continent: "Africa", flag: "🇳🇪" },
    { name: "Nigeria", continent: "Africa", flag: "🇳🇬" },
    { name: "North Korea", continent: "Asia", flag: "🇰🇵" },
    { name: "North Macedonia", continent: "Europe", flag: "🇲🇰" },
    { name: "Norway", continent: "Europe", flag: "🇳🇴" },
    { name: "Oman", continent: "Asia", flag: "🇴🇲" },
    { name: "Pakistan", continent: "Asia", flag: "🇵🇰" },
    { name: "Palau", continent: "Oceania", flag: "🇵🇼" },
    { name: "Panama", continent: "North America", flag: "🇵🇦" },
    { name: "Papua New Guinea", continent: "Oceania", flag: "🇵🇬" },
    { name: "Paraguay", continent: "South America", flag: "🇵🇾" },
    { name: "Peru", continent: "South America", flag: "🇵🇪" },
    { name: "Philippines", continent: "Asia", flag: "🇵🇭" },
    { name: "Poland", continent: "Europe", flag: "🇵🇱" },
    { name: "Portugal", continent: "Europe", flag: "🇵🇹" },
    { name: "Qatar", continent: "Asia", flag: "🇶🇦" },
    { name: "Romania", continent: "Europe", flag: "🇷🇴" },
    { name: "Russia", continent: "Europe", flag: "🇷🇺" },
    { name: "Rwanda", continent: "Africa", flag: "🇷🇼" },
    { name: "Saint Kitts and Nevis", continent: "North America", flag: "🇰🇳" },
    { name: "Saint Lucia", continent: "North America", flag: "🇱🇨" },
    { name: "Saint Vincent and the Grenadines", continent: "North America", flag: "🇻🇨" },
    { name: "Samoa", continent: "Oceania", flag: "🇼🇸" },
    { name: "San Marino", continent: "Europe", flag: "🇸🇲" },
    { name: "Sao Tome and Principe", continent: "Africa", flag: "🇸🇹" },
    { name: "Saudi Arabia", continent: "Asia", flag: "🇸🇦" },
    { name: "Senegal", continent: "Africa", flag: "🇸🇳" },
    { name: "Serbia", continent: "Europe", flag: "🇷🇸" },
    { name: "Seychelles", continent: "Africa", flag: "🇸🇨" },
    { name: "Sierra Leone", continent: "Africa", flag: "🇸🇱" },
    { name: "Singapore", continent: "Asia", flag: "🇸🇬" },
    { name: "Slovakia", continent: "Europe", flag: "🇸🇰" },
    { name: "Slovenia", continent: "Europe", flag: "🇸🇮" },
    { name: "Solomon Islands", continent: "Oceania", flag: "🇸🇧" },
    { name: "Somalia", continent: "Africa", flag: "🇸🇴" },
    { name: "South Africa", continent: "Africa", flag: "🇿🇦" },
    { name: "South Korea", continent: "Asia", flag: "🇰🇷" },
    { name: "South Sudan", continent: "Africa", flag: "🇸🇸" },
    { name: "Spain", continent: "Europe", flag: "🇪🇸" },
    { name: "Sri Lanka", continent: "Asia", flag: "🇱🇰" },
    { name: "Sudan", continent: "Africa", flag: "🇸🇩" },
    { name: "Suriname", continent: "South America", flag: "🇸🇷" },
    { name: "Sweden", continent: "Europe", flag: "🇸🇪" },
    { name: "Switzerland", continent: "Europe", flag: "🇨🇭" },
    { name: "Syria", continent: "Asia", flag: "🇸🇾" },
    { name: "Taiwan", continent: "Asia", flag: "🇹🇼" },
    { name: "Tajikistan", continent: "Asia", flag: "🇹🇯" },
    { name: "Tanzania", continent: "Africa", flag: "🇹🇿" },
    { name: "Thailand", continent: "Asia", flag: "🇹🇭" },
    { name: "Timor-Leste", continent: "Asia", flag: "🇹🇱" },
    { name: "Togo", continent: "Africa", flag: "🇹🇬" },
    { name: "Tonga", continent: "Oceania", flag: "🇹🇴" },
    { name: "Trinidad and Tobago", continent: "North America", flag: "🇹🇹" },
    { name: "Tunisia", continent: "Africa", flag: "🇹🇳" },
    { name: "Turkey", continent: "Asia", flag: "🇹🇷" },
    { name: "Turkmenistan", continent: "Asia", flag: "🇹🇲" },
    { name: "Tuvalu", continent: "Oceania", flag: "🇹🇻" },
    { name: "Uganda", continent: "Africa", flag: "🇺🇬" },
    { name: "Ukraine", continent: "Europe", flag: "🇺🇦" },
    { name: "United Arab Emirates", continent: "Asia", flag: "🇦🇪" },
    { name: "United Kingdom", continent: "Europe", flag: "🇬🇧" },
    { name: "United States", continent: "North America", flag: "🇺🇸" },
    { name: "Uruguay", continent: "South America", flag: "🇺🇾" },
    { name: "Uzbekistan", continent: "Asia", flag: "🇺🇿" },
    { name: "Vanuatu", continent: "Oceania", flag: "🇻🇺" },
    { name: "Vatican City", continent: "Europe", flag: "🇻🇦" },
    { name: "Venezuela", continent: "South America", flag: "🇻🇪" },
    { name: "Vietnam", continent: "Asia", flag: "🇻🇳" },
    { name: "Yemen", continent: "Asia", flag: "🇾🇪" },
    { name: "Zambia", continent: "Africa", flag: "🇿🇲" },
    { name: "Zimbabwe", continent: "Africa", flag: "🇿🇼" }
];

// Helper functions
function getCountriesByContinent(continent) {
    return countries.filter(country => country.continent === continent);
}

function getUniqueContinents() {
    return [...new Set(countries.map(country => country.continent))];
}

function getCountryByName(name) {
    return countries.find(country => country.name.toLowerCase() === name.toLowerCase());
}

function getRandomCountry(countryList = countries) {
    const randomIndex = Math.floor(Math.random() * countryList.length);
    return countryList[randomIndex];
}

function getCountrySuggestions(input) {
    if (!input) return [];
    const lowerInput = input.toLowerCase();
    return countries
        .filter(country => country.name.toLowerCase().startsWith(lowerInput))
        .map(country => country.name)
        .slice(0, 5);
} 